apiVersion: v1
kind: PersistentVolume
metadata:
  name: cka-static-pv
spec:
  capacity:
    storage: 256Mi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cka-static
  hostPath:
    path: /tmp/cka-static-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cka-static-pvc
  namespace: cka-storage
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 128Mi
  storageClassName: cka-static
